language: python
sudo : false
python:
    - 3.5 

services: postgresql

# Commands to install dependencies
env:
    global:
        - DJANGO_SETTINGS_MODULE=mysite.settings
        - PYTHONPATH="/home/travis/build/bfarayev/ProjectUmbrella-Code"
        - PIP_USE_MIRRORS=true

matrix:
        - DJANGO=1.10.1 DB=postgres

before_install:
    - export PIP_USE_MIRRORS=true

# Install all dependencies
install:
  - pip install -q -r requirements.txt

# Create postgres + postgis first
before_script:
  - psql -c 'create database umbrella_db;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d umbrella_db

# Command to run the test suite
script:
  - python3 manage.py test

# Notify us on Slack channel
notifications:
    slack: elec9616:HDzpNGrHAb8emioJ6TKPDgCD
