language: python

python:
    - 3.5 

services: postgresql

env:
    - DJANGO=1.10.1

before_install:
    - export DJANGO_SETTINGS_MODULE=your_project.settings
    - export PYTHONPATH=$HOME/builds/your_github_username/your_repo
    - export PIP_USE_MIRRORS=true

install:
    - pip install -r requirements.txt
    - pip install django==$DJANGO --quiet

before_script:
    - psql -c "CREATE DATABASE umbrella_db;" -U postgres

script:
    - python manage.py runserver
