language: python
sudo : false
python:
    - 3.5 

services: postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE="mysite.settings.py"
    - PYTHONPATH="/home/travis/build/bfarayev/ProjectUmbrella-Code"
    - PIP_USE_MIRRORS=true
  matrix:
    - DJANGO=1.10.1 DB=postgres

#commands to install dependencies
install:
  - pip install -q Django==$DJANGO
  - pip install -q -r requirements.txt

before_script:
  - mysql -e 'create database umbrella_db;'
  - python manage.py syncdb --noinput

#command to run the test suite
script:
  - python manage.py test
